# Generated by Django 3.1.5 on 2021-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('your_email', models.CharField(max_length=30)),
                ('your_subject', models.CharField(max_length=20)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homeimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
