# Generated by Django 3.1.5 on 2021-01-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_form_homeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
