# Generated by Django 3.1.5 on 2021-01-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_delete_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homeimage',
        ),
    ]
