# Generated by Django 3.1.5 on 2021-01-21 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_delete_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=40)),
                ('frontend', models.CharField(max_length=40)),
                ('backend', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
