# Generated by Django 3.1.5 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='githuub',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
