# Generated by Django 3.1.5 on 2021-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_pro_githuub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='githuub',
            field=models.CharField(max_length=60),
        ),
    ]
