# Generated by Django 3.1.5 on 2021-01-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20210122_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pro',
            new_name='Portfolio',
        ),
    ]
